name: ci

on: [push, pull_request, workflow_dispatch]
jobs:
    test-and-coverage:
        strategy:
          matrix:
            python-version: ['2.7', '3.12']
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install Python requirements
              run: |
                pip install --upgrade pip
                pip install pytest pytest-cov

            - name: Test
              run: pytest --cov

            - name: Coveralls
              uses: coverallsapp/github-action@v2
